# Generated by Django 3.2.13 on 2022-06-12 05:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Location of this event.', srid=4326)),
                ('event_type', models.CharField(choices=[('Sport', 'Sport'), ('Musical', 'Musical'), ('Educational', 'Educational')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('google_email', models.EmailField(editable=False, max_length=254, primary_key=True, serialize=False)),
                ('credentials', picklefield.fields.PickledObjectField(editable=False)),
                ('email', models.EmailField(max_length=254)),
                ('notify_before_days', models.IntegerField(default=1)),
                ('preference', models.TextField(blank=True, default='')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Restrict the event you receive around this location', null=True, srid=4326)),
                ('distance', models.FloatField(blank=True, help_text='Restrict the events you receive around the location by this distance, in kilometers.', null=True)),
            ],
        ),
    ]
